import java.util.List;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private ItemRepository itemRepository;
    private SalesPromotionRepository salesPromotionRepository;

    public App(ItemRepository itemRepository, SalesPromotionRepository salesPromotionRepository) {
        this.itemRepository = itemRepository;
        this.salesPromotionRepository = salesPromotionRepository;
    }

    public String bestCharge(List<String> inputs) {
        //TODO: write code here
        List<Item> itemList = itemRepository.findAll();
        List<SalesPromotion> salesPromotionList = salesPromotionRepository.findAll();
        double no_discount = 0;    //不使用任何优惠时的总价格
        double half_price_discount = 0;  //以半价优惠的标准算的总价格
        double half_price_discount_save = 0;  //以半价优惠的标准算省下的钱
        String result = "============= Order details =============\n";
        String items = "";  //显示半价商品的名称
        for (String input : inputs) {
            boolean flag = false;  //标志当前遍历商品是不是半价商品
            int num = Integer.parseInt(String.valueOf(input.charAt(input.length() - 1)));//购买的数量
            for (Item item : itemList) {
                if (item.getId().equals(input.substring(0, 8))) {  //截取id
                    result += item.getName() + " x "
                            + num + " = "
                            + (int) item.getPrice() * num + " yuan\n";
                    no_discount += item.getPrice() * num;
                    for (String relatedItem : salesPromotionList.get(1).getRelatedItems()) {  //get(1)才可获得半价优惠的信息
                        if (item.getId().equals(relatedItem)) {
                            half_price_discount += item.getPrice() * num / 2;
                            half_price_discount_save += item.getPrice() * num / 2;
                            flag = true;        //是半价商品
                            if (items.equals(""))        //如果show本身是"",即添加为第一个，不需要在前面加逗号
                                items += item.getName();
                            else
                                items += "，" + item.getName();
                            break;
                        }
                    }
                    if (!flag) {        //如果上面if不是半价商品flag就会是false，加上原价
                        half_price_discount += item.getPrice() * num;
                    }
                    break;

                }
            }
        }
        result += "-----------------------------------\n";

        if (no_discount>=30&&no_discount-6 <= half_price_discount) {
            result += "Promotion used:\n" +
                    "满30减6 yuan，saving 6 yuan\n" +
                    "-----------------------------------\n" +
                    "Total：" + (int) (no_discount-6) + " yuan\n" +
                    "===================================";
        } else if (half_price_discount_save != 0) {
            result += "Promotion used:\n" +
                    "Half price for certain dishes (" + items + ")，saving " + (int) half_price_discount_save + " yuan\n" +
                    "-----------------------------------\n" +
                    "Total：" + (int) half_price_discount + " yuan\n" +
                    "===================================";
        } else {
            result += "Total：" + (int) no_discount + " yuan\n" +
                    "===================================";
        }
        return result;
    }

}
